name: .NET Core # will work, but only show the text and not the value $[env.nameVar] 
# ${{ env.nameVar }} this one will not start

on: 
  push:
  
  workflow_dispatch: 

env:
  nameVar: "[name from var]"

jobs:
  build-and-deploy:
    #name: Testing with ${{ env.nameVar }} this one will not start
    environment: Production

    runs-on: ubuntu-latest

    steps:
    - run: echo "GITHUB_WORKFLOW=Workflow name from step" >> $GITHUB_ENV
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.0.100
    - name: DevSkim
      uses: microsoft/DevSkim-Action@v1
      with:
        output-directory: ./output
        
    - name: Trufflehog Check
      uses: UnicornGlobal/trufflehog-actions-scan@v1.0.0
      
    - name: flawfinder_scan
  # You may pin to the exact commit or the version.
  # uses: david-a-wheeler/flawfinder@8e4a779ad59dbfaee5da586aa9210853b701959c
      uses: david-a-wheeler/flawfinder@2.0.19-alpha1
      with:
        output: ./output/FlawFinder.txt
        
    - name: Archive code coverage results
      uses: actions/upload-artifact@v2
      with:
        name: code-coverage-report
        path: output/
    
    # dotnet build and publish
    - name: Build with dotnet ${{ env.nameVar }}
      run: |
        dotnet build --configuration Release ./dotnet-core-webapp/dotnetcore-webapp.csproj
      
    - name: dotnet publish
      run: |
        dotnet publish -c Release -o dotnetcorewebapp ./dotnet-core-webapp
        
    # test for usage in versioning
    - name: Hello world
      run: echo Hello world, run number = $NBR
      env: 
        NBR: ${{ github.RUN_NUMBER }}
        
