name: .NET Core # will work, but only show the text and not the value $[env.nameVar] 
# ${{ env.nameVar }} this one will not start

on: 
  push:
  
  workflow_dispatch: 

env:
  nameVar: "[name from var]"

jobs:
  build-and-deploy:
    #name: Testing with ${{ env.nameVar }} this one will not start
    environment: Production

    runs-on: ubuntu-latest

    steps:
    - run: echo "GITHUB_WORKFLOW=Workflow name from step" >> $GITHUB_ENV
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.0.100
    - name: DevSkim
      uses: microsoft/DevSkim-Action@v1
      with:
        output-directory: ./
        
    - name: Archive code coverage results
      uses: actions/upload-artifact@v2
      with:
        name: code-coverage-report
        path: output/
    
    # dotnet build and publish
    - name: Build with dotnet ${{ env.nameVar }}
      run: |
        dotnet build --configuration Release ./dotnet-core-webapp/dotnetcore-webapp.csproj

    - name: dotnet publish
      run: |
        dotnet publish -c Release -o dotnetcorewebapp ./dotnet-core-webapp
        
    # test for usage in versioning
    - name: Hello world
      run: echo Hello world, run number = $NBR
      env: 
        NBR: ${{ github.RUN_NUMBER }}
        
    - name: Deploy
      uses: azure/webapps-deploy@v2
      with:
        publish-profile: ${{ secrets.PUBLISHPROFILE }}
